Feature/load apfel
N3PDF/banana pull request #13
Opened 2021-03-02 09:34 UTC by giacomomagni

More generic ```load apfel``` function compatible also with ekomark

2021-03-02 10:16 UTC, felixhekhorn requested changes

2021-03-02 10:16 UTC, felixhekhorn commented on src/banana/benchmark/external/apfel_utils.py
> +        apfel.InitializeAPFEL()
keep the front-end specific stuff out of banana - simply call the rest in ekomark for example and add the ``apfel.InitializeAPFEL()`` there

2021-03-02 10:16 UTC, felixhekhorn commented on src/banana/benchmark/external/apfel_utils.py
> +def load_apfel(theory, observables, pdf="ToyLH", prDIS=True):
do you mean ocard?

2021-03-03 10:34 UTC, AleCandido approved these changes

2021-03-03 10:39 UTC, merged